# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default: task --list --taskfile "{{.ROOT_DIR}}/.taskfiles/validate/Taskfile.yaml"

  build-push-image:
    desc: Builds and pushes a sample image to the local registry
    silent: true
    vars:
      IMAGE_EXISTS:
        sh: |
          if {{.RUNTIME_BINARY}} manifest inspect {{.REGISTRY_HOST}}/{{.REGISTRY_NAME}}-test:{{.IMAGE_TAG}} >/dev/null 2>&1; then
            echo "true"
          else
            echo "false"
          fi
    cmds:
      - |
        if [ "{{.IMAGE_EXISTS}}" = "true" ]; then
          echo "ℹ️ Image {{.REGISTRY_HOST}}/{{.REGISTRY_NAME}}-test:{{.IMAGE_TAG}} already exists in registry"
        else
          echo "🔄 Building and pushing a sample image to local registry..."
          {{.RUNTIME_BINARY}} build {{.REG_TEST_DIR}} -t {{.REGISTRY_HOST}}/{{.REGISTRY_NAME}}-test:{{.IMAGE_TAG}} >/dev/null
          {{.RUNTIME_BINARY}} push {{.REGISTRY_HOST}}/{{.REGISTRY_NAME}}-test:{{.IMAGE_TAG}} >/dev/null
          echo "✅ Sample image built and pushed successfully"
        fi

  deploy-test-app:
    desc: Deploy a sample Helm release using an image from the local registry
    silent: true
    cmds:
      - |
        if helm get values {{.REGISTRY_NAME}}-test -n default -o yaml 2>/dev/null | grep -q "tag: {{.IMAGE_TAG}}"; then
          echo "ℹ️ Helm release {{.REGISTRY_NAME}}-test with image tag {{.IMAGE_TAG}} already deployed"
        else
          echo "🔄 Deploying a test app Helm release based on image tag {{.IMAGE_TAG}}..."
          helm upgrade --install --wait {{.REGISTRY_NAME}}-test bjw-s/app-template \
            --version {{.APP_TEMPLATE_VERSION}} --namespace default \
            --values <(cat << EOF
        controllers:
          main:
            type: deployment
            strategy: RollingUpdate
            containers:
              main:
                image:
                  repository: {{.REGISTRY_HOST}}/{{.REGISTRY_NAME}}-test
                  tag: {{.IMAGE_TAG}}
                env:
                  - name: IMAGE_TAG
                    value: {{.IMAGE_TAG}}
        service:
          main:
            controller: main
            ports:
              http:
                port: 80
        ingress:
          main:
            enabled: true
            className: nginx
            hosts:
              - host: {{.REGISTRY_NAME}}-test.{{.LOCAL_DOMAIN}}
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http
            tls:
              - hosts:
                  - {{.REGISTRY_NAME}}-test.{{.LOCAL_DOMAIN}}
        EOF
        )
          echo "✅ Test app Helm release based on image tag {{.IMAGE_TAG}} deployed successfully"
        fi

  undeploy-test-app:
    desc: Undeploy the test app Helm release
    silent: true
    cmds:
      - echo "🔄 Undeploying sample app helm release..."
      - |
        if helm status {{.REGISTRY_NAME}}-test -n default >/dev/null 2>&1; then
          echo "  ⏳ Uninstalling helm release '{{.REGISTRY_NAME}}-test'..."
          helm uninstall {{.REGISTRY_NAME}}-test -n default
          echo "  ✅ Helm release '{{.REGISTRY_NAME}}-test' uninstalled"
        else
          echo "ℹ️ Helm release '{{.REGISTRY_NAME}}-test' is not installed"
        fi
      - echo "✅ Sample app helm release undeployed"

  local-registry:
    desc: "Validates local registry by building and pushing an image, then deploying a Helm release using that image"
    vars:
      IMAGE_TAG:
        sh: |
          # Create hash from both files
          cat {{.REG_TEST_DIR}}/ep.sh {{.REG_TEST_DIR}}/Dockerfile | sha256sum | cut -c1-8
    cmds:
      - task: build-push-image
        vars: { IMAGE_TAG: '{{.IMAGE_TAG}}' }
      - task: deploy-test-app
        vars: { IMAGE_TAG: '{{.IMAGE_TAG}}' }

  app:
    desc: Validates sample app deployed via Helm release from local registry
    silent: true
    vars:
      TEST_NAME: "{{.REGISTRY_NAME}}-test"
    cmds:
      - echo "🔄 Validating sample application..."
      - sleep 5
      - echo -e "\n🌐 Registry Test (https://{{.TEST_NAME}}.{{.LOCAL_DOMAIN}}/):\n"
      - curl -s https://{{.TEST_NAME}}.{{.LOCAL_DOMAIN}}/
      - echo "✅ Sample application validation complete"

  tcp-services:
    desc: "Validate TCP services are reachable from local machine"
    silent: true
    cmds:
      - |
        echo "🔍 Validating enabled TCP services from local machine:"
        FAILED=0
        ENABLED_SERVICES=($(yq e '.environment.services[] | select(.enabled == true) | .name' {{.CONFIG_FILE}}))
        for service in "${ENABLED_SERVICES[@]}"; do
          ports=($(yq e ".environment.services[] | select(.name == \"$service\") | .ports[]" {{.CONFIG_FILE}}))
          for port in "${ports[@]}"; do
            echo "  🔄 Validating $service on port $port..."
            if nc -zv $service.{{.LOCAL_DOMAIN}} $port; then
              echo "  ✅ $service is reachable on port $port"
            else
              echo "  ❌ $service is NOT reachable on port $port"
              FAILED=1
            fi
          done
        done
        
        if [ $FAILED -eq 1 ]; then
          echo "❌ Some services are not reachable from local machine"
          exit 1
        fi
        echo "✅ All services are reachable from local machine"