# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  check:
    desc: Check and install required dependencies
    silent: true
    cmds:
      - echo "🔄 Checking dependencies..."
      - mise install
      - mise run deps
      - echo "✅ Dependencies check complete"

  deps:
    desc: Install Python dependencies
    silent: true
    cmds:
      - echo "🔄 Installing Python dependencies..."
      - mise run deps
      - echo "✅ Python dependencies installed" 