# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default: task --list --taskfile "{{.ROOT_DIR}}/.taskfiles/help/Taskfile.yaml"

  cluster-info:
    desc: "Show basic info about the kubernetes cluster"
    silent: true
    cmds:
      - "echo 🏢 Cluster Name: {{.CLUSTER_NAME}}"
      - |
        if {{.PROVIDER_BINARY}} get clusters 2>/dev/null | grep -q "{{.CLUSTER_NAME}}"; then
          kubectl --kubeconfig {{.KUBECONFIG_PATH}} cluster-info
        else
          echo "ℹ️ Cluster {{.CLUSTER_NAME}} does not exist"
        fi

  environment:
    desc: "Show environment configuration details"
    silent: true
    cmds:
      - |
        echo "🌍 Environment Configuration:"
        echo "├── Name: {{.ENV_NAME}}"
        echo "├── Base Directory: {{.BASE_DIR}}"
        echo "├── Local Domain: {{.LOCAL_DOMAIN}}"
        echo "├── Local IP: {{.LOCAL_IP}}"
        echo "├── Container Runtime: {{.RUNTIME}}"
        echo "├── Nodes:"
        echo "│   ├── Control Plane: {{.SERVERS}}"
        echo "│   ├── Workers: {{.WORKERS}}"
        echo "│   └── Control Plane Scheduling: {{.ALLOW_CP_SCHEDULING}}"
        echo "└── Service Presets Enabled: {{.USE_SERVICE_PRESETS}}"

  services:
    desc: "Show information about enabled services"
    silent: true
    cmds:
      - |
        echo "🔌 Enabled Services:"
        yq e '.environment.services[] | select(.enabled == true) | "├── " + .name + ": " + (.ports | join(", "))' {{.CONFIG_FILE}}
        echo "└── Registry: {{.REGISTRY_HOST}}"

  dns:
    desc: "Show DNS configuration"
    silent: true
    cmds:
      - |
        echo "🔍 DNS Configuration:"
        echo "├── Container Name: {{.DNS_CONTAINER_NAME}}"
        echo "├── Status: $( {{.RUNTIME_BINARY}} ps --filter name={{.DNS_CONTAINER_NAME}} --format '{{`{{.Status}}`}}' || echo 'Not running' )"
        echo "└── Config File: {{.K8S_DIR}}/config/dnsmasq.conf"
        
        if [ -f "{{.K8S_DIR}}/config/dnsmasq.conf" ]; then
          echo -e "\n📄 DNS Records:"
          grep "address=/" {{.K8S_DIR}}/config/dnsmasq.conf | sed 's/address=\//├── /'
        fi

  storage:
    desc: "Show storage information"
    silent: true
    cmds:
      - |
        echo "💾 Storage Information:"
        echo "├── Base Path: {{.K8S_DIR}}/storage"
        echo "├── Control Plane Storage:"
        for i in $(seq 0 $(expr {{.SERVERS}} - 1)); do
          SIZE=$(du -sh {{.K8S_DIR}}/storage/control-$i 2>/dev/null | cut -f1 || echo "N/A")
          echo "│   ├── control-$i: $SIZE"
        done
        echo "└── Worker Storage:"
        for i in $(seq 0 $(expr {{.WORKERS}} - 1)); do
          SIZE=$(du -sh {{.K8S_DIR}}/storage/worker-$i 2>/dev/null | cut -f1 || echo "N/A")
          echo "    ├── worker-$i: $SIZE"
        done

  certificates:
    desc: "Show certificate information"
    silent: true
    cmds:
      - |
        echo "🔐 Certificate Information:"
        echo "├── CA Path: {{.ROOT_CA_PATH}}"
        echo "├── Certificates Directory: {{.K8S_DIR}}/certs"
        if [ -f "{{.K8S_DIR}}/certs/{{.LOCAL_DOMAIN}}.pem" ]; then
          echo "├── Domain Certificate:"
          openssl x509 -in {{.K8S_DIR}}/certs/{{.LOCAL_DOMAIN}}.pem -noout -subject -issuer -dates | sed 's/^/│   ├── /'
        fi
        echo "└── Wildcard TLS Secret Status:"
        if {{.PROVIDER_BINARY}} get clusters 2>/dev/null | grep -q "{{.CLUSTER_NAME}}" && test -f {{.KUBECONFIG_PATH}}; then
          if kubectl --kubeconfig {{.KUBECONFIG_PATH}} get secret wildcard-tls -n kube-system >/dev/null 2>&1; then
            SECRET=$(kubectl --kubeconfig {{.KUBECONFIG_PATH}} get secret wildcard-tls -n kube-system -o json)
            echo "    ├── Name: $(echo "$SECRET" | jq -r '.metadata.name')"
            echo "    ├── Namespace: $(echo "$SECRET" | jq -r '.metadata.namespace')"
            echo "    └── Age: $(echo "$SECRET" | jq -r '.metadata.creationTimestamp')"
          else
            echo "    └── Not found"
          fi
        else
          echo "    └── Cluster not available"
        fi

  logs:
    desc: "Show logs information and recent logs"
    silent: true
    cmds:
      - |
        echo "📝 Logs Information:"
        echo "├── Base Path: {{.K8S_DIR}}/logs"
      - task: _show_node_logs
        vars:
          NODE_TYPE: control
          PREFIX: "│"
          TITLE: "Control Plane Logs:"
          COUNT: "{{.SERVERS}}"
      - task: _show_node_logs
        vars:
          NODE_TYPE: worker
          PREFIX: " "
          TITLE: "Worker Logs:"
          COUNT: "{{.WORKERS}}"

  _show_node_logs:
    internal: true
    silent: true
    cmds:
      - |
        echo "{{if eq .NODE_TYPE "control"}}├{{else}}└{{end}}── {{.TITLE}}"
        for i in $(seq 0 $(expr {{.COUNT}} - 1)); do
          LOG_DIR="{{.K8S_DIR}}/logs/{{.NODE_TYPE}}-$i"
          if [ -d "$LOG_DIR" ]; then
            SIZE=$(du -sh "$LOG_DIR" 2>/dev/null | cut -f1 || echo "N/A")
            echo "{{.PREFIX}}   ├── {{.NODE_TYPE}}-$i:"
            echo "{{.PREFIX}}   │   ├── Size: $SIZE"
            # Check containers directory
            if [ -d "$LOG_DIR/containers" ] && [ -n "$(ls -A $LOG_DIR/containers 2>/dev/null)" ]; then
              echo "{{.PREFIX}}   │   ├── Container Logs:"
              ls -t "$LOG_DIR/containers" | head -n 3 | sed 's/^/{{.PREFIX}}   │   │   ├── /'
            fi
            # Check pods directory
            if [ -d "$LOG_DIR/pods" ] && [ -n "$(ls -A $LOG_DIR/pods 2>/dev/null)" ]; then
              echo "{{.PREFIX}}   │   └── Pod Logs:"
              ls -t "$LOG_DIR/pods" | head -n 3 | sed 's/^/{{.PREFIX}}   │       ├── /'
            else
              echo "{{.PREFIX}}   │   └── No logs present"
            fi
          fi
        done

  all:
    desc: "Show all environment information"
    silent: true
    cmds:
      - task: environment
      - echo ""
      - task: cluster-info
      - echo ""
      - task: services
      - echo ""
      - task: dns
      - echo ""
      - task: storage
      - echo ""
      - task: logs
      - echo ""
      - task: certificates

  setup-completions:
    desc: "Configure shell completions for installed tools"
    silent: true
    vars:
      SHELL_NAME:
        sh: ps -p $PPID -o comm= | sed 's/^-//'
    cmds:
      - |
        echo "🔄 Setting up shell completions..."
        case "{{.SHELL_NAME}}" in
          bash)
            task help:setup-completions-bash
            ;;
          zsh)
            task help:setup-completions-zsh
            ;;
          fish)
            task help:setup-completions-fish
            ;;
          *)
            echo "❌ Unsupported shell: {{.SHELL_NAME}}"
            exit 1
            ;;
        esac
        echo "✅ Shell completions configured"
        echo "👉 Please restart your shell or source your shell rc file to enable completions"

  setup-completions-bash:
    desc: "Configure tools completions for the bash shell"
    silent: true
    vars:
      COMPLETION_DIR: "$HOME/.local/share/bash-completion/completions"
      SHELL_RC: "$HOME/.bashrc"
    status:
      - test -d "{{.COMPLETION_DIR}}"
      - test -f "{{.COMPLETION_DIR}}/task.bash"
      - test -f "{{.COMPLETION_DIR}}/kubectl.bash"
      - test -f "{{.COMPLETION_DIR}}/helm.bash"
      - test -f "{{.COMPLETION_DIR}}/kind.bash"
      - test -f "{{.COMPLETION_DIR}}/helmfile.bash"
      - test -f "{{.COMPLETION_DIR}}/kustomize.bash"
      - test -f "{{.COMPLETION_DIR}}/yq.bash"
      - |
        grep -q "source.*task.bash" "{{.SHELL_RC}}" && \
        grep -q "source.*kubectl.bash" "{{.SHELL_RC}}" && \
        grep -q "source.*helm.bash" "{{.SHELL_RC}}" && \
        grep -q "source.*kind.bash" "{{.SHELL_RC}}" && \
        grep -q "source.*helmfile.bash" "{{.SHELL_RC}}" && \
        grep -q "source.*kustomize.bash" "{{.SHELL_RC}}" && \
        grep -q "source.*yq.bash" "{{.SHELL_RC}}"
    cmds:
      - |
        mkdir -p "{{.COMPLETION_DIR}}"
        
        # Task completion
        task --completion bash > "{{.COMPLETION_DIR}}/task.bash"
        grep -q "source.*task.bash" "{{.SHELL_RC}}" || echo "source {{.COMPLETION_DIR}}/task.bash" >> "{{.SHELL_RC}}"
        
        # Kubectl completion
        kubectl completion bash > "{{.COMPLETION_DIR}}/kubectl.bash"
        grep -q "source.*kubectl.bash" "{{.SHELL_RC}}" || echo "source {{.COMPLETION_DIR}}/kubectl.bash" >> "{{.SHELL_RC}}"
        grep -q "alias k=kubectl" "{{.SHELL_RC}}" || echo "alias k=kubectl" >> "{{.SHELL_RC}}"
        grep -q "complete -o default -F __start_kubectl k" "{{.SHELL_RC}}" || echo "complete -o default -F __start_kubectl k" >> "{{.SHELL_RC}}"
        
        # Helm completion
        helm completion bash > "{{.COMPLETION_DIR}}/helm.bash"
        grep -q "source.*helm.bash" "{{.SHELL_RC}}" || echo "source {{.COMPLETION_DIR}}/helm.bash" >> "{{.SHELL_RC}}"
        
        # Kind completion
        kind completion bash > "{{.COMPLETION_DIR}}/kind.bash"
        grep -q "source.*kind.bash" "{{.SHELL_RC}}" || echo "source {{.COMPLETION_DIR}}/kind.bash" >> "{{.SHELL_RC}}"
        
        # Helmfile completion
        helmfile completion bash > "{{.COMPLETION_DIR}}/helmfile.bash"
        grep -q "source.*helmfile.bash" "{{.SHELL_RC}}" || echo "source {{.COMPLETION_DIR}}/helmfile.bash" >> "{{.SHELL_RC}}"
        
        # Kustomize completion
        kustomize completion bash > "{{.COMPLETION_DIR}}/kustomize.bash"
        grep -q "source.*kustomize.bash" "{{.SHELL_RC}}" || echo "source {{.COMPLETION_DIR}}/kustomize.bash" >> "{{.SHELL_RC}}"
        
        # YQ completion
        yq shell-completion bash > "{{.COMPLETION_DIR}}/yq.bash"
        grep -q "source.*yq.bash" "{{.SHELL_RC}}" || echo "source {{.COMPLETION_DIR}}/yq.bash" >> "{{.SHELL_RC}}"

  setup-completions-zsh:
    desc: "Configure tools completions for the zsh shell"
    silent: true
    vars:
      COMPLETION_DIR: "$HOME/.local/share/zsh/site-functions"
      SHELL_RC: "$HOME/.zshrc"
    status:
      - test -d "{{.COMPLETION_DIR}}"
      - test -f "{{.COMPLETION_DIR}}/_task"
      - test -f "{{.COMPLETION_DIR}}/_kubectl"
      - test -f "{{.COMPLETION_DIR}}/_helm"
      - test -f "{{.COMPLETION_DIR}}/_kind"
      - test -f "{{.COMPLETION_DIR}}/_helmfile"
      - test -f "{{.COMPLETION_DIR}}/_kustomize"
      - test -f "{{.COMPLETION_DIR}}/_yq"
      - grep -q "^fpath=" "{{.SHELL_RC}}"
      - grep -q "^autoload -Uz compinit" "{{.SHELL_RC}}"
      - grep -q "^compinit" "{{.SHELL_RC}}"
    cmds:
      - |
        mkdir -p "{{.COMPLETION_DIR}}"
        
        # Create or update zsh completion configuration
        ZSH_COMP_CONFIG=$(cat << 'EOF'

        # Completion configuration
        fpath=({{.COMPLETION_DIR}} $fpath)
        autoload -Uz compinit
        compinit

        # Aliases and their completions
        alias k=kubectl
        compdef k=kubectl
        EOF
        )
        
        # Add completion config if not present
        if ! grep -q "^fpath=" "{{.SHELL_RC}}"; then
          echo "$ZSH_COMP_CONFIG" >> "{{.SHELL_RC}}"
        fi
        
        # Task completion
        task --completion zsh > "{{.COMPLETION_DIR}}/_task"
        
        # Kubectl completion
        kubectl completion zsh > "{{.COMPLETION_DIR}}/_kubectl"
        
        # Helm completion
        helm completion zsh > "{{.COMPLETION_DIR}}/_helm"
        
        # Kind completion
        kind completion zsh > "{{.COMPLETION_DIR}}/_kind"
        
        # Helmfile completion
        helmfile completion zsh > "{{.COMPLETION_DIR}}/_helmfile"
        
        # Kustomize completion
        kustomize completion zsh > "{{.COMPLETION_DIR}}/_kustomize"
        
        # YQ completion
        yq shell-completion zsh > "{{.COMPLETION_DIR}}/_yq"

  setup-completions-fish:
    desc: "Configure tools completions for the fish shell"
    silent: true
    vars:
      COMPLETION_DIR: "$HOME/.config/fish/completions"
    status:
      - test -d "{{.COMPLETION_DIR}}"
      - test -f "{{.COMPLETION_DIR}}/task.fish"
      - test -f "{{.COMPLETION_DIR}}/kubectl.fish"
      - test -f "{{.COMPLETION_DIR}}/helm.fish"
      - test -f "{{.COMPLETION_DIR}}/kind.fish"
      - test -f "{{.COMPLETION_DIR}}/helmfile.fish"
      - test -f "{{.COMPLETION_DIR}}/kustomize.fish"
      - test -f "{{.COMPLETION_DIR}}/yq.fish"
    cmds:
      - |
        mkdir -p "{{.COMPLETION_DIR}}"
        
        # Task completion
        task --completion fish > "{{.COMPLETION_DIR}}/task.fish"
        
        # Kubectl completion
        kubectl completion fish > "{{.COMPLETION_DIR}}/kubectl.fish"
        mkdir -p "$HOME/.config/fish/conf.d"
        echo "alias k=kubectl" > "$HOME/.config/fish/conf.d/kubectl.fish"
        echo "complete -c k -w kubectl" >> "$HOME/.config/fish/conf.d/kubectl.fish"
        
        # Helm completion
        helm completion fish > "{{.COMPLETION_DIR}}/helm.fish"
        
        # Kind completion
        kind completion fish > "{{.COMPLETION_DIR}}/kind.fish"
        
        # Helmfile completion
        helmfile completion fish > "{{.COMPLETION_DIR}}/helmfile.fish"
        
        # Kustomize completion
        kustomize completion fish > "{{.COMPLETION_DIR}}/kustomize.fish"
        
        # YQ completion
        yq shell-completion fish > "{{.COMPLETION_DIR}}/yq.fish"
