# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default: task --list --taskfile "{{.ROOT_DIR}}/.taskfiles/status/Taskfile.yaml"

  cluster-info:
    desc: "Show basic info about the kubernetes cluster"
    silent: true
    cmds:
      - "echo ðŸ¢ Cluster Name: {{.CLUSTER_NAME}}"
      - |
        if {{.PROVIDER_BINARY}} get clusters 2>/dev/null | grep -q "{{.CLUSTER_NAME}}"; then
          kubectl --kubeconfig {{.KUBECONFIG_PATH}} cluster-info
        else
          echo "â„¹ï¸ Cluster {{.CLUSTER_NAME}} does not exist"
        fi

  environment:
    desc: "Show environment configuration details"
    silent: true
    cmds:
      - |
        echo "ðŸŒ Environment Configuration:"
        echo "â”œâ”€â”€ Name: {{.ENV_NAME}}"
        echo "â”œâ”€â”€ Base Directory: {{.BASE_DIR}}"
        echo "â”œâ”€â”€ Local Domain: {{.LOCAL_DOMAIN}}"
        echo "â”œâ”€â”€ Local IP: {{.LOCAL_IP}}"
        echo "â”œâ”€â”€ Container Runtime: {{.RUNTIME}}"
        echo "â”œâ”€â”€ Nodes:"
        echo "â”‚   â”œâ”€â”€ Control Plane: {{.SERVERS}}"
        echo "â”‚   â”œâ”€â”€ Workers: {{.WORKERS}}"
        echo "â”‚   â”œâ”€â”€ Allow Control Plane Scheduling: {{.ALLOW_CONTROL_PLANE_SCHEDULING}}"
        echo "â”‚   â””â”€â”€ Run Services on Workers Only: {{.RUN_SERVICES_ON_WORKERS_ONLY}}"
        echo "â””â”€â”€ Service Presets Enabled: {{.USE_SERVICE_PRESETS}}"

  services:
    desc: "Show information about enabled services"
    silent: true
    cmds:
      - |
        echo "ðŸ”Œ Enabled Services:"
        
        # Show system services
        SYSTEM_SERVICES=$(yq e '.environment.services.system[] | select(.enabled == true) | .name' {{.CONFIG_FILE}} 2>/dev/null || echo "")
        if [ -n "$SYSTEM_SERVICES" ]; then
          echo "â”œâ”€â”€ System Services (with presets):"
          yq e '.environment.services.system[] | select(.enabled == true) | "â”‚   â”œâ”€â”€ " + .name + ": " + (.ports | join(", "))' {{.CONFIG_FILE}}
        else
          echo "â”œâ”€â”€ System Services: None enabled"
        fi
        
        # Show user services
        USER_SERVICES=$(yq e '.environment.services.user[] | select(.enabled == true) | .name' {{.CONFIG_FILE}} 2>/dev/null || echo "")
        if [ -n "$USER_SERVICES" ]; then
          echo "â”œâ”€â”€ User Services (custom configuration):"
          yq e '.environment.services.user[] | select(.enabled == true) | "â”‚   â”œâ”€â”€ " + .name + " (namespace: " + (.namespace // .name) + ")"' {{.CONFIG_FILE}}
        else
          echo "â”œâ”€â”€ User Services: None enabled"
        fi
        
        echo "â””â”€â”€ Registry: {{.REGISTRY_HOST}}"

  dns:
    desc: "Show DNS configuration"
    silent: true
    cmds:
      - |
        echo "ðŸ” DNS Configuration:"
        echo "â”œâ”€â”€ Container Name: {{.DNS_CONTAINER_NAME}}"
        echo "â”œâ”€â”€ Status: $( {{.RUNTIME_BINARY}} ps --filter name={{.DNS_CONTAINER_NAME}} --format '{{`{{.Status}}`}}' || echo 'Not running' )"
        echo "â””â”€â”€ Config File: {{.K8S_DIR}}/config/dnsmasq.conf"
        
        if [ -f "{{.K8S_DIR}}/config/dnsmasq.conf" ]; then
          echo -e "\nðŸ“„ DNS Records:"
          grep "address=/" {{.K8S_DIR}}/config/dnsmasq.conf | sed 's/address=\//â”œâ”€â”€ /'
        fi

  storage:
    desc: "Show storage information"
    silent: true
    cmds:
      - |
        echo "ðŸ’¾ Storage Information:"
        echo "â”œâ”€â”€ Base Path: {{.K8S_DIR}}/storage"
        echo "â”œâ”€â”€ Control Plane Storage:"
        for i in $(seq 0 $(expr {{.SERVERS}} - 1)); do
          SIZE=$(du -sh {{.K8S_DIR}}/storage/control-$i 2>/dev/null | cut -f1 || echo "N/A")
          echo "â”‚   â”œâ”€â”€ control-$i: $SIZE"
        done
        echo "â””â”€â”€ Worker Storage:"
        for i in $(seq 0 $(expr {{.WORKERS}} - 1)); do
          SIZE=$(du -sh {{.K8S_DIR}}/storage/worker-$i 2>/dev/null | cut -f1 || echo "N/A")
          echo "    â”œâ”€â”€ worker-$i: $SIZE"
        done

  certificates:
    desc: "Show certificate information"
    silent: true
    cmds:
      - |
        echo "ðŸ” Certificate Information:"
        echo "â”œâ”€â”€ CA Path: {{.ROOT_CA_PATH}}"
        echo "â”œâ”€â”€ Certificates Directory: {{.K8S_DIR}}/certs"
        
        # Check for root CA certificate
        if [ -f "{{.K8S_DIR}}/certs/rootCA.pem" ]; then
          echo "â”œâ”€â”€ Root CA Certificate:"
          openssl x509 -in {{.K8S_DIR}}/certs/rootCA.pem -noout -subject -issuer -dates | sed 's/^/â”‚   â”œâ”€â”€ /'
        fi
        
        # Check for domain certificates
        if [ -f "{{.K8S_DIR}}/certs/dev.me.pem" ]; then
          echo "â”œâ”€â”€ Domain Certificate:"
          openssl x509 -in {{.K8S_DIR}}/certs/dev.me.pem -noout -subject -issuer -dates | sed 's/^/â”‚   â”œâ”€â”€ /'
        fi

  logs:
    desc: "Show logs information and recent logs"
    silent: true
    cmds:
      - |
        echo "ðŸ“ Logs Information:"
        echo "â”œâ”€â”€ Base Path: {{.K8S_DIR}}/logs"
      - task: _show_node_logs
        vars:
          NODE_TYPE: control
          PREFIX: "â”‚"
          TITLE: "Control Plane Logs:"
          COUNT: "{{.SERVERS}}"
      - task: _show_node_logs
        vars:
          NODE_TYPE: worker
          PREFIX: " "
          TITLE: "Worker Logs:"
          COUNT: "{{.WORKERS}}"

  _show_node_logs:
    internal: true
    silent: true
    cmds:
      - |
        echo "{{if eq .NODE_TYPE "control"}}â”œ{{else}}â””{{end}}â”€â”€ {{.TITLE}}"
        for i in $(seq 0 $(expr {{.COUNT}} - 1)); do
          LOG_DIR="{{.K8S_DIR}}/logs/{{.NODE_TYPE}}-$i"
          if [ -d "$LOG_DIR" ]; then
            SIZE=$(du -sh "$LOG_DIR" 2>/dev/null | cut -f1 || echo "N/A")
            echo "{{.PREFIX}}   â”œâ”€â”€ {{.NODE_TYPE}}-$i:"
            echo "{{.PREFIX}}   â”‚   â”œâ”€â”€ Size: $SIZE"
            # Check containers directory
            if [ -d "$LOG_DIR/containers" ] && [ -n "$(ls -A $LOG_DIR/containers 2>/dev/null)" ]; then
              echo "{{.PREFIX}}   â”‚   â”œâ”€â”€ Container Logs:"
              ls -t "$LOG_DIR/containers" | head -n 3 | sed 's/^/{{.PREFIX}}   â”‚   â”‚   â”œâ”€â”€ /'
            fi
            # Check pods directory
            if [ -d "$LOG_DIR/pods" ] && [ -n "$(ls -A $LOG_DIR/pods 2>/dev/null)" ]; then
              echo "{{.PREFIX}}   â”‚   â””â”€â”€ Pod Logs:"
              ls -t "$LOG_DIR/pods" | head -n 3 | sed 's/^/{{.PREFIX}}   â”‚       â”œâ”€â”€ /'
            else
              echo "{{.PREFIX}}   â”‚   â””â”€â”€ No logs present"
            fi
          fi
        done

  all:
    desc: "Show all environment information"
    silent: true
    cmds:
      - task: environment
      - echo ""
      - task: cluster-info
      - echo ""
      - task: services
      - echo ""
      - task: dns
      - echo ""
      - task: storage
      - echo ""
      - task: logs
      - echo ""
      - task: certificates
